CC=gcc

all: main.o utilidades.o
	$(CC) main.o utilidades.o -o cadastro

main.o: src/main.c
	$(CC) -c src/main.c -o main.o
utilidades.o: src/utilidades.c
	$(CC) -c src/utilidades.c -o utilidades.o

clean:
	rm *.o cadastro
